version: 2
log-file: /home/tiennguyen/.cache/efm.log
log-level: 2
root-markers:
  - .git/
  - go.mod
  - go.work

tools:
  golangci-lint: &golangci-lint
    lint-command: "golangci-lint run --show-stats=false --output.text.print-issued-lines=false --output.text.path=stdout --output.text.colors=false"
    lint-formats:
      - "%f:%l:%c: %m"
    lint-stdin: false
    lint-workspace: true
    lint-severity: 2
    lint-ignore-exit-code: false
    lint-source: "golangci"
  golangci-fmt: &golangci-fmt
    format-command: "golangci-lint fmt --stdin --color='never'"
    format-stdin: true
  prettierd: &prettierd
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} \
        ${--tab-width=tabSize}
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

languages:
  go:
    - <<: *golangci-lint
    - <<: *golangci-fmt
  gotmpl:
    - <<: *golangci-lint
    - <<: *golangci-fmt
  gomod:
    - <<: *golangci-fmt
  gowork:
    - <<: *golangci-fmt
  html:
    - <<: *prettierd
  css:
    - <<: *prettierd
  json:
    - <<: *prettierd
  js:
    - <<: *prettierd
  jsx:
    - <<: *prettierd
  ts:
    - <<: *prettierd
  markdown:
    - <<: *prettierd
  yaml:
    - <<: *prettierd
