version: 2
log-file: /home/tiennguyen/.cache/efm.log
log-level: 2
root-markers:
  - .git/
  - go.mod
  - go.work

tools:
  golangci-lint: &golangci-lint
    lint-command: "golangci-lint run --show-stats=false --output.text.print-issued-lines=false --output.text.path=stdout --output.text.colors=false"
    lint-formats:
      - "%f:%l:%c: %m"
    lint-stdin: false
    lint-workspace: true
    lint-severity: 2
    lint-ignore-exit-code: false
    lint-source: "golangci"
  golangci-fmt: &golangci-fmt
    format-command: "golangci-lint fmt --stdin --color='never' --enable='gofumpt,goimports'"
    format-stdin: true
  prettier: &prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${INPUT}"
    format-stdin: true

languages:
  go:
    - <<: *golangci-lint
    - <<: *golangci-fmt
  gotmpl:
    - <<: *golangci-lint
    - <<: *golangci-fmt
  gomod:
    - <<: *golangci-fmt
  gowork:
    - <<: *golangci-fmt
  html:
    - <<: *prettier
  css:
    - <<: *prettier
  json:
    - <<: *prettier
  js:
    - <<: *prettier
  jsx:
    - <<: *prettier
  ts:
    - <<: *prettier
  markdown:
    - <<: *prettier
  yaml:
    - <<: *prettier
