version: 2
log-file: /home/tiennguyen/.cache/efm.log
log-level: 2
root-markers:
  - .git/
  - go.mod
  - go.work

tools:
  golangci-lint: &golangci-lint
    lint-command: "golangci-lint run --show-stats=false --output.text.print-issued-lines=false --output.text.path=stdout --output.text.colors=false"
    lint-formats:
      - "%f:%l:%c: %m"
    lint-stdin: false
    lint-workspace: true
    lint-severity: 2
    lint-ignore-exit-code: true
    lint-source: "golangci"
  golangci-fmt: &golangci-fmt
    format-command: "golangci-lint fmt --stdin --color='never' --enable='goimports,gofumpt'"
    format-stdin: true
  css-prettier: &css-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser css"
    format-stdin: true
  html-prettier: &html-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser html"
    format-stdin: true
  json-prettier: &json-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser json"
    format-stdin: true
  js-prettier: &js-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser meriyah"
    format-stdin: true
  ts-prettier: &ts-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser typescript"
    format-stdin: true
  yaml-prettier: &yaml-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser yaml"
    format-stdin: true

languages:
  go:
    - <<: *golangci-lint
    - <<: *golangci-fmt
  gotmpl:
    - <<: *golangci-lint
    - <<: *golangci-fmt
  gomod:
    - <<: *golangci-fmt
  gowork:
    - <<: *golangci-fmt
  yaml:
    - <<: *yaml-prettier
  html:
    - <<: *html-prettier
  css:
    - <<: *css-prettier
  json:
    - <<: *json-prettier
  javascript:
    - <<: *js-prettier
  typescript:
    - <<: *ts-prettier
  # jsx:
  #   - <<: *prettier
